all: revert "sys/fuchsia: update system calls for bti, cache, iommu, pmt, and process (#3321)"
This has broken our CI tests:

fatal error: 'lib/ddk/driver.h' file not found

That's indeed an error and it needs to be fixed, but for now it just
stops syzkaller development.