tools/syz-usbgen: fix usb_ids.patch
Previous patch causes build error on top of v5.14:

error: ‘usb_bus_type’ undeclared (first use in this function); did you mean ‘hid_bus_type’?
 2299 |         bus_for_each_drv(&usb_bus_type, NULL, NULL, usb_device_id_dump_driver);
      |                           ^~~~~~~~~~~~
      |                           hid_bus_type

Fix it by including drivers/usb/core/usb.h where usb_bus_type declaration
is. Also, removed duplicate is_usb_device_driver definition, since it's
already in drivers/usb/core/usb.h.

Tested localy on qemu

Signed-off-by: Pavel Skripkin <paskripkin@gmail.com>