executor: unbreak on OpenBSD
Commit 09c6f48e ("all: support extra coverage") broke the executor on OpenBSD:

  executor/executor.cc:61:11: error: unused variable 'kExtraCoverSize' [-Werror,-Wunused-const-variable]
  const int kExtraCoverSize = 256 << 10;