dashboard: make qemu arm64 configs compile again
We've been running into the following error:

error: static declaration of 'mem_encrypt_init' follows non-static declaration

The problem was caused by Kconfig not being able to adjust the
depenencies, the fix is already coming:

https://lore.kernel.org/lkml/CANp29Y6AnNeouWgAevBEDZcYcOjzDQwxLDfLxe41Lp3BC=h8bA@mail.gmail.com/T/

After it's merged, we'll have to update our configs anyway. So let's do
it now.